### ISSUE TITLE
Suggestion: Change of the command name to cropchecker

### ISSUE THREAD

**Issue by CloudeLecaw** [steve4744/CropChecker#1]
Hi There, i allready wrote this on spigot, but on Github its mostly seen earlier by the developers 

May i can suggest to change the commandname

currently it is **/cc** -> You may should change it to **/cropchecker**?
Why? On Most Servers /cc is used to clear the chat (ClearChat)
Also you can aspect that normaly you will not use this command very often, specialy because its just to reload the config.
Normaly after doing this once, you dont do it aggain.

**Comment by steve4744** [comment]
That's a good point - I'd forgotten about ClearChat. I'll change it in the next release.

**Comment by steve4744** [comment]
Fixed in version 1.8, commit e3f212a.
